spring.application.name=imc-pediatrico

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/imc_pediatrico
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true